//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordGamePuzzle.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PlayBookDataContext : DbContext
    {
        public PlayBookDataContext()
            : base("name=PlayBookDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ethnicity> Ethnicities { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<WordCombination> WordCombinations { get; set; }
        public virtual DbSet<WordsDictionary> WordsDictionaries { get; set; }
    
        public virtual ObjectResult<Nullable<int>> usp_CheckCombinationCount(Nullable<int> source_id, Nullable<int> target_id)
        {
            var source_idParameter = source_id.HasValue ?
                new ObjectParameter("source_id", source_id) :
                new ObjectParameter("source_id", typeof(int));
    
            var target_idParameter = target_id.HasValue ?
                new ObjectParameter("target_id", target_id) :
                new ObjectParameter("target_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_CheckCombinationCount", source_idParameter, target_idParameter);
        }
    
        public virtual int usp_UpdateValueCount(Nullable<int> comb_id)
        {
            var comb_idParameter = comb_id.HasValue ?
                new ObjectParameter("comb_id", comb_id) :
                new ObjectParameter("comb_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateValueCount", comb_idParameter);
        }
    
        public virtual int usp_InsertIntoWordsDictionary(string word_desc, Nullable<int> sourceword_id, Nullable<int> userword_id, Nullable<int> gender_id, Nullable<int> eth_id)
        {
            var word_descParameter = word_desc != null ?
                new ObjectParameter("word_desc", word_desc) :
                new ObjectParameter("word_desc", typeof(string));
    
            var sourceword_idParameter = sourceword_id.HasValue ?
                new ObjectParameter("sourceword_id", sourceword_id) :
                new ObjectParameter("sourceword_id", typeof(int));
    
            var userword_idParameter = userword_id.HasValue ?
                new ObjectParameter("userword_id", userword_id) :
                new ObjectParameter("userword_id", typeof(int));
    
            var gender_idParameter = gender_id.HasValue ?
                new ObjectParameter("gender_id", gender_id) :
                new ObjectParameter("gender_id", typeof(int));
    
            var eth_idParameter = eth_id.HasValue ?
                new ObjectParameter("eth_id", eth_id) :
                new ObjectParameter("eth_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertIntoWordsDictionary", word_descParameter, sourceword_idParameter, userword_idParameter, gender_idParameter, eth_idParameter);
        }
    
        public virtual int usp_InsertIntoWordsMaster(string word_desc, ObjectParameter sourceword_id)
        {
            var word_descParameter = word_desc != null ?
                new ObjectParameter("word_desc", word_desc) :
                new ObjectParameter("word_desc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertIntoWordsMaster", word_descParameter, sourceword_id);
        }
    }
}
