//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordGamePuzzle.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordCombination
    {
        public int comb_id { get; set; }
        public int key1 { get; set; }
        public int key2 { get; set; }
        public int gender_id { get; set; }
        public int eth_id { get; set; }
        public Nullable<int> ValueCount { get; set; }
    
        public virtual Ethnicity Ethnicity { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual WordsDictionary WordsDictionary { get; set; }
        public virtual WordsDictionary WordsDictionary1 { get; set; }
    }
}
